name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: [self-hosted, windows, x64]

    environment: preprod

    defaults:
      run:
        working-directory: environments/preprod

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        shell: powershell
        run: terraform init
        working-directory: environments/preprod

      - name: Terraform Format
        shell: powershell
        run: terraform fmt -check
        working-directory: environments/preprod

      - name: Terraform Validate
        shell: powershell
        run: terraform validate
        working-directory: environments/preprod

      - name: Terraform Plan
        shell: powershell
        run: terraform plan
        working-directory: environments/preprod


  terraform-apply:
    name: Terraform Apply
    runs-on: [self-hosted, windows, x64]

    needs: terraform-plan

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    environment: preprod

    defaults:
      run:
        working-directory: environments/preprod

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        shell: powershell
        run: terraform init
        working-directory: environments/preprod
      - name: Terraform Apply
        shell: powershell
        run: terraform apply -auto-approve
        working-directory: environments/preprod